export const CREATE_INGREDIENTS_REQUEST = "CREATE_INGREDIENTS_REQUEST";
export const CREATE_INGREDIENTS_SUCCESS = "CREATE_INGREDIENTS_SUCCESS";
export const CREATE_INGREDIENTS_FAILURE = "CREATE_INGREDIENTS_FAILURE";

export const CREATE_INGREDIENTS_CATEGORY_REQUEST =
  "CREATE_INGREDIENTS_CATEGORY_REQUEST";
export const CREATE_INGREDIENTS_CATEGORY_SUCCESS =
  "CREATE_INGREDIENTS_CATEGORY_SUCCESS";
export const CREATE_INGREDIENTS_CATEGORY_FAILURE =
  "CREATE_INGREDIENTS_CATEGORY_FAILURE";

export const GET_INGREDIENTS_CATEGORY_REQUEST =
  "GET_INGREDIENTS_CATEGORY_REQUEST";
export const GET_INGREDIENTS_CATEGORY_SUCCESS =
  "GET_INGREDIENTS_CATEGORY_SUCCESS";
export const GET_INGREDIENTS_CATEGORY_FAILURE =
  "GET_INGREDIENTS_CATEGORY_FAILURE";

export const GET_INGREDIENTS = "get_Ingredients";
export const UPDATE_STOCK = "UPADATE_STOK";
